ItStep/first/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView, \
    PasswordChangeView, PasswordChangeDoneView, \
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView


urlpatterns = [
    path('accounts/login/', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),

    path('accounts/password_change', PasswordChangeView.as_view(template_name='user/change_password.html'),
         name='password_change'),
    path('accounts/password_change/done', PasswordChangeDoneView.as_view(template_name='user/changed_password.html'),
         name='password_change_done'),


    path('accounts/password_reset/', PasswordResetView.as_view(template_name='user/reset.html',
                                                               subject_template_name='emails/header.txt',
                                                               email_template_name='emails/body.txt'),
         name='reset_password'),
    path('accounts/password_reset/done/', PasswordResetDoneView.as_view(template_name='user/reset_sent.html'),
         name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>', PasswordResetConfirmView.as_view(template_name='user/reset_form.html'),
         name='password_reset_confirm'),
    path('accounts/reset/done', PasswordResetCompleteView.as_view(template_name='user/reset_done.html'),
         name='password_reset_complete'),


    path('', include('main.urls')),
    #path('bboard/', include('main.urls', namespace='new-bboard')),
    path('users/', include('user.urls')),
    path('templates/', include('temp_app.urls')),
    path('admin/', admin.site.urls),
]


ItStep/temp_app/urls.py
from django.urls import path, re_path
from . import views


app_name = 'temp'
urlpatterns = [
    path('change_all/', views.change, name="change_all"),
    path('detail/<slug:slug>', views.TempDetail.as_view(), name="detail-temp"),
    path('detail/edit/<slug:slug>', views.edit, name="edit"),
    path('create/', views.TempCreateView.as_view(), name="create"),
    path('test/', views.testindex, name='test'),
    path('delete/<slug:slug>', views.create_Temp, name='delete'),
    path('update/<slug:slug>', views.create_Temp, name='update'),
    path('', views.TempListView.as_view(), name='index'),
    # create temp
    # update temp
    # delete temp

]

ItStep/user/urls.py
from django.urls import path, re_path
from . import views


app_name = 'user'
urlpatterns = [
    path('user-<slug:slug>/', views.UserDetailView.as_view(), name='user-info'),
    path('new-user/', views.UserAddView.as_view(), name='new-user'),
    path('', views.UserListView.as_view(), name='index'),
]

ItStep/temp_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class TempManager(models.Manager):
    def get_high_to_low(self):
        return super().get_queryset().order_by('-price')

    def get_low_to_high(self):
        return super().get_queryset().order_by('price')

    def order_by_title(self):
        return super().get_queryset().order_by('title')

    def order_by_published_fresh(self):
        return super().get_queryset().order_by('-published')

    def order_by_published_old(self):
        return super().get_queryset().order_by('published')

#from temp_app.models import Temp
#Temp.objects.order_by_title()
#Temp.tmp.get_queryset()
#Temp.objects.get_high_to_low()


class Note(models.Model):
    title = models.CharField(max_length=15)
    content = models.TextField()
    email = models.EmailField()
    date = models.DateField()

    class Meta:
        verbose_name_plural = 'Текст'
        verbose_name = 'Тексты'
        abstract = True


class Note_1(Note): # Абстрактное наследование от Note
    class Meta(Note.Meta):
        pass


class PrivateNote(Note): # Абстрактное наследование от Note
    #title = models.CharField(max_length=25)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=500)
    email = None
    date = None

    class Meta(Note.Meta):
        pass


class Message_from_abstract(Note): # Абстрактное наследование от Note
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    email = None
    date = None
    title = None

    class Meta(Note.Meta):
        verbose_name_plural = 'Сообщение'
        verbose_name = 'Сообщения'


class Message(models.Model):
    content = models.TextField()


class PrivateMessage(Message): # Прямое наследование от Message
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    #message = models.OneToOneField(Message, on_delete=models.CASCADE, parent_link=True)
    #from temp_app.models import PrivateMessage
    #from django.contrib.auth.models import User
    #usr = User.objects.get(username='1')
    #pm = PrivateMessage.objects.create(content='some text from head', user=usr)
    #pm.content
    #pm.user
    # m = pm.message_ptr
    #m.privatemessage


class Temp(models.Model):
    order = models.SmallIntegerField(default=0, db_index=True)
    title = models.CharField(max_length=50, verbose_name='Товар')
    content = models.TextField(null=True, blank=True, verbose_name='Описание')
    price = models.FloatField(null=True, blank=True, verbose_name='Цена')
    published = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')
    slug = models.SlugField("url", max_length=200, unique=True)
    objects = TempManager()
    tmp_main = models.Manager()
    tmp = TempManager()

    class Meta:
        verbose_name_plural = 'Темплэйты'
        verbose_name = 'Темплэйт'
        ordering = ['order', '-published', 'title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("temp:detail-temp", kwargs={"slug": self.slug})


class ReverseTemp(Temp): # Прокси - модель наследуемся от Temp
    #title = models.CharField() НЕ РАБОТАЕТ!!!

    class Meta:
        proxy = True
        ordering = ['-order']

ItStep/temp_app/forms.py
from django.core.exceptions import ValidationError
from django.forms import modelform_factory, DecimalField, ModelForm, modelformset_factory
from django.forms.widgets import Select, __all__
from django import forms
from django.core import validators
from django.http import HttpResponse

from .models import Temp

Temp1Form = modelform_factory(Temp,
                              fields=('title',  'slug',),
                              exclude=('published', 'price', 'content',),
                              labels={'title': 'Название Темплэйта', 'price': 'Ценник', 'slug':'unique url'},
                              error_messages={ValidationError: {
                                            'slug': 'slug is not unique',
                                             'title': 'title is not defined',
                                             'price': 'price is not valid',
                                             'content': 'content is not valid',
                                             'published': 'time wrong'}},
                              help_texts={'slug': 'Должно быть уникальным', 'content':'пожалуйста заполни' },
                              field_classes={'price': DecimalField, })




class Temp2Form(ModelForm):
    class Meta:
        model = Temp
        fields = ('title', 'price', 'content', 'slug')
        labels = {'title': 'Название Темплэйта', 'price': 'Ценник', 'slug': 'unique url'}
        error_messages = {ValidationError: {
            'slug': 'slug is not unique',
            'title': 'title is not defined',
            'price': 'price is not valid',
            'content': 'content is not valid',
            'published': 'time wrong'}}
        help_texts = {'slug': 'Должно быть уникальным', 'content': 'пожалуйста заполни'}
        field_classes = {'price': DecimalField, }


def myvalidator(val):
    if val != 'AAAA':
        raise ValidationError('title is not correct')


class Temp3Form(forms.ModelForm):
    title = forms.CharField(
        label='Название темплейта',
        max_length=50,
        #validators=[myvalidator],
        #validators=[validators.RegexValidator(regex='^.{4,}$')],
        error_messages={'invalid': 'Слишком короткое название'})
    #price = forms.DecimalField(label='ценник', decimal_places=3)
    #content = forms.CharField(label='Содержимое темплейта', widget=forms.Textarea)
    slug = forms.SlugField(label='адрес', help_text='Должно быть уникальным')
    #published = forms.DateTimeField(label='', help_text='', label_suffix='', initial='', required=True, widget=Select, validators='', error_messages={},  )

    class Meta:
        model = Temp
        fields = ('title', 'slug')

    def clean(self):
        super().clean()
        errors = {}
        if self.cleaned_data['title'] == 'BB' or self.cleaned_data['title'] == 'AA':
            errors['title'] = ValidationError('title is not allowed')
        #if self.cleaned_data['price'] <= 0:
        #    errors['title'] = ValidationError('Fill in the price correctly')
        if errors:
            raise ValidationError(errors)


class Temp4Form(forms.ModelForm):
    title = forms.CharField(label='Название темплейта', max_length=50, initial='some price')
    price = forms.DecimalField(label='ценник', decimal_places=2, label_suffix='|------->', initial=0, required=False, disabled=True )

    class Meta:
        model = Temp
        fields = ('title', 'price', 'content', 'slug')


formset = modelformset_factory(Temp,
                               form=Temp1Form,
                               #fields=('title', 'slug',),
                               #exclude=('content', 'published', 'price', ),
                               #error_messages=
                               #help_texts=
                               #labels=
                               #changed_objects, new_objects, deleted_objects
                               extra=1, can_order=True, can_delete=True,
                               min_num=1, validate_min=True,
                               max_num=100, validate_max=True,
                               )



ItStep/temp_app/views.py
from django.contrib.auth.decorators import user_passes_test
from django.core.paginator import Paginator
from django.forms.formsets import ORDERING_FIELD_NAME
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from .models import Temp, ReverseTemp
from .forms import Temp1Form, Temp2Form, Temp3Form, Temp4Form, formset
from django.db import transaction


def commit_handler():
    print('commit successful')

@user_passes_test(lambda user: user.is_staff)
#@transaction.atomic
def change(request):
    param = []
    if request.method == 'POST':
        TempFormSet = formset(request.POST)
        if TempFormSet.is_valid():
            #with transaction.atomic():
            for form in TempFormSet:
                if form.cleaned_data:
                    sp = transaction.savepoint()
                        #with transaction.atomic():
                    try:
                        temp = form.save(commit=False)
                        temp.order = form.cleaned_data[ORDERING_FIELD_NAME]
                        temp.save()
                        transaction.savepoint(sp)
                    except:
                        transaction.savepoint_rollback(sp)
                    transaction.commit()
                    transaction.on_commit(commit_handler)
            #for temp in TempFormSet.changed_objects:
            #for temp in TempFormSet.new_objects:
            TempFormSet.save(commit=False)
            for temp in TempFormSet.deleted_objects:
                temp.delete()
            return HttpResponseRedirect('/templates')
    else:
        TempFormSet = formset()

    context = {'formset': TempFormSet}
    return render(request, 'temp_app/formset.html', context)


def edit(request, slug):
    tp = Temp.objects.get(slug=slug)
    if request.method == 'POST':
        tpf = Temp3Form(request.POST, instance=tp)
        if tpf.is_valid():
            try:
                content = tpf.cleaned_data['content']
                tpf.save()
                tp.content = content
                tp.save()
                #if content.contains(ругательства):
                #    transaction.rollback()
                #else:
                transaction.commit()
            except:
                transaction.rollback()
            return HttpResponseRedirect(reverse('temp:detail-temp', kwargs={'slug': tpf.cleaned_data['slug']}))
        else:
            context = {'form': tpf}
            html = '<h1>Incorrect form</h1><a href="<slug:slug>"><input type="submit" value="Исправить"></a>'
            html = html.replace('<slug:slug>', str(slug))
            return HttpResponse(html)
            #return render(request, 'temp_app/create.html', context)
    else:
        tpf = Temp3Form(instance=tp)
        context = {'form': tpf}
        return render(request, 'temp_app/create.html', context)



class TempCreateView(CreateView):
    form_class = Temp3Form
    template_name = "temp_app/create.html"
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


def testindex(request):
    temps = Temp.objects.all()
    amount = 2
    paginator = Paginator(temps, amount)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1

    page = paginator.get_page(page_num)

    #print(paginator.count)
    #print(paginator.num_pages)
    #print(paginator.page_range)

    #print(paginator.get_page(3))
    #print(paginator.page(3))
    #print(paginator.get_page(0))
    #print(paginator.get_page(90))
    #print(paginator.page(0.3))
    #print(page.object_list)
    #print(page.number)
    #print(page.paginator)
    #print(page.has_next())
    #print(page.has_previous())
    #print(page.has_other_pages())
    #print(page.next_page_number())
    #print(page.previous_page_number())
    #print(page.start_index())
    #print(page.end_index())

    context = {'page': page, 'temps': page.object_list}
    return render(request, 'temp_app/testindex.html', context)


class TempDetail(DetailView):
    model = Temp
    context_object_name = "tmp"
    template_name = "temp_app/detail.html"


@transaction.non_atomic_requests
class TempListView(ListView):
    model = Temp
    template_name = 'temp_app/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Tmps'] = Temp.objects.all()
        return context


def create_Temp(request):
    model = Temp
    tf = Temp4Form(request.POST)
    if tf.is_valid():
        tf.save()

    return HttpResponseRedirect(reverse_lazy("temp:detail-temp", kwargs={"slug": tf.cleaned_data['slug']}))


#css_path = 'temp_app/main.css'

#STATIC_URL+css_path --->'static/temp_app/main.css'
# Create your views here.

ItStep/temp_app/templates/temp_app/base.html
<!doctype html>
<html lang="ru">
<head>
    <title>{% block title %}Главная{% endblock %}:: Доска объявлений</title>
</head>
<body bgcolor="ccffcc", text="00331a", link="cc0000", vlink="4d0000">

<h1>Записи</h1>
<nav>
    <a href="{% url 'temp:index' %}">main page</a>
    <a href="{% url 'temp:create' %}">create</a>
    <a href="{% url 'temp:change_all' %}">change all</a>
    <a href="{% url 'temp:test' %}">test</a>
</nav>
{% block content %}
{% endblock %}
</body>
</html>


ItStep/temp_app/templates/temp_app/create.html
{% extends "temp_app/base.html" %}
{% block content %}
 <h1>Добавление Темплейта</h1>
    {% if form.is_multipart %}
        <form enctype="multipart/form-data" method="post">
    {% else %}
        <form method="post">
    {% endif %}
        <table>
            {% csrf_token %}
            {{ form }}
            {% for hidden in form.hidden_fields %}
            {{ hidden }}
            {% endfor %}
        </table>
        <input type="submit" value="Добавить">
    </form>
{% endblock %}

ItStep/temp_app/templates/temp_app/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

ItStep/temp_app/templates/temp_app/detail.html
{% extends "temp_app/base.html" %}

{%block content%}
<h1>Template</h1>
    <h4><a href="{% url 'temp:edit' tmp.slug %}"> {{tmp.title}}</a></h4>
    <h5> {{ tmp.content }} </h5>
    <h6> {{ tmp.price }} </h6>
    <h6> {{ tmp.slug }} </h6>
    <h3> {{ tmp.published|date:"d.m.Y H:i:s" }} </h3>
{% endblock %}

ItStep/temp_app/templates/temp_app/examples.html
{% url 'app_name:name' param=param_self.pk %}
{% if obj1 == obj2 %}
{% if obj1 != obj2 %}
{% if obj1 >=< obj2 %}
{% if obj1 in obj2 %}
{% if obj1 not in obj2 %}
{% if obj1 Is obj2 %}
{% if obj1 is not obj2 %}

{% elif %}
{% else %}
{% endif  %}



{% for rubric in rubrics %}
{% ifchanged %}{{ rubric.parent.name }}{% endifchanged %}
...
{% endfor %}

{% for rubric in rubrics %}
{% ifchanged rubric.parent %}
    {{ rubric.parent.name }}
{% endifchanged %}
...
{% endfor %}


{% for rubric in rubrics %}
<div class="{% cycle 'obj1' 'obj2' 'obj3' %}">
    <h3>{{ rubric.name }}</h3>
    <h3>{{ rubric.parent }}</h3>
</div>
{% endfor %}

.myDiv1 {
border: 5px outset red;
background-color: black;
text-align: right
}
.myDiv2 {
border: 5px outset red;
background-color: black;
text-align: left
}

.myrub1{
border: 5px outset red;
}
.myrub2{
border: 5px outset red;
}


{% for rubric in rubrics %}
<div class="{% cycle 'myDiv1' 'myDiv2' %}">
    {% if rubric.name Is 'Instruments' %}
    <h3 class="myrub1">{{ rubric.name }}</h3>
    <h3>{{ rubric.parent }}</h3>
    {% elif rubric.name Is 'Books' %}
    <h3 class="myrub2">{{ rubric.name }}</h3>
    <h3>{{ rubric.parent }}</h3>
    ...
    {% else %}
    <h3>{{ rubric.name }}</h3>
    <h3>{{ rubric.parent }}</h3>
    {% endif %}

</div>
{% endfor %}

{% for rubric in rubrics %}
<h4>{{ forloop.counter }}</h4>
<h4>{{ forloop.counter0 }}</h4>
<h4>{{ forloop.revcounter0 }}</h4>
<h4>{{ forloop.revcounter }}</h4>
<h4>{{ forloop.first }}</h4>
<h4>{{ forloop.last }}</h4>

    {% if {{ forloop.last }} %}
    <div class="lastclass">
        ...
    </div>
    {% elif {{ forloop.first }} %}
    <div class="firstclass">
        ...
    </div>
    {% endif %}
{% empty %}
<h1>В рубриках ничего нет!!!</h1>
{% endfor %}


{% for bb in bbs %}
    ...
    {{ forloop }}
    {% for r in rubrics %}
        <p>{{ r.name }}</p>
        <h4>{{ forloop.parentloop.counter0 }}</h4>
        {% empty %}
        <h1>В рубриках ничего нет!!!</h1>
    {% endfor %}
{% endfor %}


<h4>{{ forloop.first|yesno:'Правда, Ложь' }}</h4>
<h4>{{ forloop.last|yesno:'Правда, Ложь' }}</h4>
<h4> {{tmp.content|default:'свяжитесь с продавцом' }} </h4>
<h4> {{tmp.title|cut:'it'}} </h4>
{% for tmp in Tmps|dictsort:'price' %}


BASE
{% block secret %}
 <h1>secret</h1>
{% endblock %}

INDEX
{% block secret %}
    <h1>This is an updated</h1>
    {{ block.super }}
    <h1>Specifically for this page</h1>
{% endblock %}


<div class="col-md-8 col-xs-12 productPaging noPadding printHide">
    <ul class="pagination pull-right"><li class="active"><a href="#">PAGE</a></li>
        <li class="active"><a href="#"><strong>1</strong></a></li>
        <li><a href="https://www.amresupply.com/manufacturers/401510/48/48/" title="Whirlpool Parts">
                    2</a></li>
                    <li><a href="https://www.amresupply.com/manufacturers/401510/48/96/" title="Whirlpool Parts">
                    3</a></li>
                    <li><a href="https://www.amresupply.com/manufacturers/401510/48/144/" title="Whirlpool Parts">
                    4</a></li>
                    <li><a href="https://www.amresupply.com/manufacturers/401510/48/192/" title="Whirlpool Parts">
                    5</a></li>
                    <li><a href="https://www.amresupply.com/manufacturers/401510/48/48/" title="Whirlpool Parts">
                    NEXT</a></li>
                 <li><a href="https://www.amresupply.com/manufacturers/401510/48/1872/" title="Whirlpool Parts">
                    LAST</a></li>
        </ul></div>

ItStep/temp_app/templates/temp_app/formset.html
{% extends "temp_app/base.html" %}
{% block content %}
 <h1>Редактирование темплейтов</h1>
    <form method="post">
        {% csrf_token %}
        <ul>
            <table>
        {{ formset.as_table }}
            </table>
        </ul>
        <input type="submit" value="изменить">
    </form>
{% endblock %}

ItStep/temp_app/templates/temp_app/index.html
{% extends "temp_app/base.html" %}
{% load static %}

{%block content%}
{% for tmp in Tmps %}
    <h4><a href="{% url 'temp:edit' tmp.slug %}"> {{tmp.title}}</a></h4>
    <h4> {{tmp.content|default:'свяжитесь с продавцом' }} </h4>
    <h6> {{tmp.price}} </h6>
    <h5><a href="{{ tmp.get_absolute_url }}">{{ tmp.get_absolute_url }}</a></h5>
{% endfor %}
{% endblock %}


ItStep/temp_app/templates/temp_app/testindex.html
{% extends "temp_app/base.html" %}
{% load static %}

{%block content%}
<div>
  {% if page.has_previous %}
 <h6> <a href="?page={{ page.previous_page_number }}">Предыдущая</a></h6>
  &nbsp;&nbsp;| &nbsp;&nbsp;
  <h6>Страница № {{ page.number }} из {{ page.paginator.num_pages }}</h6>
  {% endif %}
  {% if page.has_next %}
  &nbsp;&nbsp;| &nbsp;&nbsp;
  <a href="?page={{ page.next_page_number }}">Следующая</a>
  {% endif %}
</div>
{% for tmp in temps %}
    <h4> {{tmp.title}} </h4>
    <h4> {{tmp.content|default:'свяжитесь с продавцом' }} </h4>
    <h6> {{tmp.price}} </h6>
    <h5><a href="{{ tmp.get_absolute_url }}">{{ tmp.get_absolute_url }}</a></h5>
{% endfor %}
{% endblock %}

ItStep/temp_app/templates/temp_app/update.html
{% extends "temp_app/index.html" %}