ItStep/first/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView, \
    PasswordChangeView, PasswordChangeDoneView, \
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView


urlpatterns = [
    path('accounts/login/', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),

    path('accounts/password_change', PasswordChangeView.as_view(template_name='user/change_password.html'),
         name='password_change'),
    path('accounts/password_change/done', PasswordChangeDoneView.as_view(template_name='user/changed_password.html'),
         name='password_change_done'),


    path('accounts/password_reset/', PasswordResetView.as_view(template_name='user/reset.html',
                                                               subject_template_name='emails/header.txt',
                                                               email_template_name='emails/body.txt'),
         name='reset_password'),
    path('accounts/password_reset/done/', PasswordResetDoneView.as_view(template_name='user/reset_sent.html'),
         name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>', PasswordResetConfirmView.as_view(template_name='user/reset_form.html'),
         name='password_reset_confirm'),
    path('accounts/reset/done', PasswordResetCompleteView.as_view(template_name='user/reset_done.html'),
         name='password_reset_complete'),


    path('', include('main.urls')),
    #path('bboard/', include('main.urls', namespace='new-bboard')),
    path('users/', include('user.urls')),
    path('templates/', include('temp_app.urls')),
    path('admin/', admin.site.urls),
]


ItStep/user/urls.py
from django.urls import path, re_path
from . import views


app_name = 'user'
urlpatterns = [
    path('user-<slug:slug>/', views.UserDetailView.as_view(), name='user-info'),
    path('new-user/', views.UserAddView.as_view(), name='new-user'),
    path('', views.UserListView.as_view(), name='index'),
]

ItStep/user/models.py
from django.db import models
from django.urls import reverse


class User(models.Model):
    #superuser = models.ForeignKey(Rubric_new, verbose_name="Рубрика2", null=True, blank=True, on_delete=models.CASCADE)
    slug = models.SlugField("username", max_length=50, unique=True)
    name = models.CharField(null=True, blank=True, max_length=30, verbose_name='Имя')
    surname = models.CharField(null=True, blank=True, max_length=30, verbose_name='Фамилия')
    date_of_birth = models.DateField(null=True, blank=True, verbose_name='Дата рождения')
    email = models.EmailField(null=True, blank=True, verbose_name='Электронная почта')
    telephone = models.CharField(null=True, blank=True, max_length=15, verbose_name='Телефон')
    registered = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Зарегистрирован')

    class Meta:
        verbose_name_plural = 'Пользователи'
        verbose_name = 'Пользователь'
        ordering = ['-registered']

    def __str__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse("user:user-info", kwargs={"slug": self.slug})

ItStep/user/forms.py
from django.forms import ModelForm
from .models import User


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ('slug', 'name', 'surname', 'date_of_birth', 'email', 'telephone')

ItStep/user/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import ListView, DetailView, FormView
from .models import User
from .forms import UserForm


class UserAddView(FormView):
    template_name = 'user/create.html'
    form_class = UserForm
    initial = {
        'slug': 'login',
        'name': 'name',
        'surname': 'surname',
        'date_of_birth': '01/01/1999',
        'email': 'mail@mail.ru',
        'telephone': '+7(---)--- -- --'
    }

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['users'] = User.objects.all()
        return context

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_form(self, form_class=None):
        self.object = super().get_form(form_class)
        return self.object

    def get_success_url(self):
        #return reverse('user:user-info', kwargs={'username': self.object.cleaned_data['username']})
        return reverse('user:index')


class UserListView(ListView):
    template_name = 'user/index.html'
    model = User

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = User.objects.all()
        return context


class UserDetailView(DetailView):
    template_name = 'user/user.html'
    model = User
    context_object_name = "user"


def login(request):
    return render(request, 'user/login.html')





ItStep/user/templates/user/base.html
{% load static %}
{% load mptt_tags %}
<!doctype html>
<html lang="ru">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'main/static/main/style.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Главная{% endblock %}:: Users</title>
</head>
<body>

<h1>Пользователи</h1>
<nav>
    <a href="{% url 'index' %}">Главная</a>
    <a href="{% url 'user:index' %}">all users</a>
    <a href="{% url 'login' %}">login</a>
    <a href="{% url 'logout' %}">logout</a>
    <a href="{% url 'user:new-user' %}">Add user</a>

</nav>
{% block content %}
{% endblock %}
<style contenteditable
       style="display: block;
        white-space: pre;">
    html{
    background: #F5F5DC;
    color: black
    font-size: 16px;
    font-family: 'Comic sans ms';
    }
</style>
</body>
</html>

ItStep/user/templates/user/change_password.html
{% extends "user/base.html" %}
{% block content %}
 <h1>Change password</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden", name="next" value="{{ next }}">
        <input type="submit" value="Изменить" >
    </form>
{% endblock %}

ItStep/user/templates/user/changed_password.html
{% extends "user/base.html" %}
{% block content %}
<h1>Success!</h1>
 <a href="{% url 'index' %}">На главную</a>
{% endblock %}


ItStep/user/templates/user/create.html
{% extends "user/base.html" %}
{% block content %}
 <h1>Добавление Пользователя</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Добавить" href="{% url 'user:index' %}">
    </form>
{% endblock %}

ItStep/user/templates/user/index.html
{% extends "user/base.html" %}
{% block content %}
{% for user in users %}
<article>
    <div>
        <h2><a href="{{ user.get_absolute_url }}"> {{ user }}</a></h2>
        <p>{{ user.name }}</p>
        <p>{{ user.surname }}</p>
        <p>*************************</p>
    </div>
</article>
{% endfor %}
{% endblock %}


ItStep/user/templates/user/login.html
{% extends "user/base.html" %}
{% block title %}Authorisation{% endblock %}
{% block content %}
<h3>Log in</h3>
{% if user.is_authenticated %}
<p>Log in successful</p>
{% else %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden", name="next" value="{{ next }}">
    <input type="submit" value="Log in">
</form>
<a href="{% url 'reset_password' %}"><i>Forgot Password?</i></a>
{% endif %}
{% endblock %}

ItStep/user/templates/user/reset.html
{% extends "user/base.html" %}
{% block content %}
<h1>Password Reset Page</h1>
<form action="" method="POST" class="text-center">
  {% csrf_token %}
  {{form}}
  <input type="submit" value="Send email" /><br>
</form>
<a href="{% url 'index' %}">Return to home page</a>
{% endblock %}

ItStep/user/templates/user/reset_done.html
{% extends "user/base.html" %}
{% block content%}
<h1>Password reset complete</h1>
<a href="{% url 'login' %}">Login</a>
{% endblock%}

ItStep/user/templates/user/reset_form.html
{% extends "user/base.html" %}
{% block content%}
<h1>Password Reset Form</h1>
<form action="" method="POST">
  {% csrf_token %} 
  {{form}}
  <input type="submit" value="Reset Password"/>
</form>

{% endblock%}

ItStep/user/templates/user/reset_sent.html
{% extends "user/base.html" %}
{% block content%}
<h1>Password reset sent</h1>
<a href="{% url 'index' %}">Return to home page</a>
{% endblock%}

ItStep/user/templates/user/user.html
{% extends "user/base.html" %}
{% block content %}
<article>
    <div>
        <h2>{{ user }}</h2>
        <p>{{ user.name }}</p>
        <p>{{ user.surname }}</p>
        <p>{{ user.email }}</p>
        <p>{{ user.registered|date:"d.m.Y H:i:s" }}</p>
    </div>
</article>
{% endblock %}